Traceback (most recent call last):
  File "/home/aquathi/.local/share/pipx/venvs/jupyter-book/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/aquathi/.local/share/pipx/venvs/jupyter-book/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aquathi/.local/share/pipx/venvs/jupyter-book/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/aquathi/.local/share/pipx/venvs/jupyter-book/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/aquathi/.local/share/pipx/venvs/jupyter-book/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/aquathi/.local/share/pipx/venvs/jupyter-book/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
gp, gv, gr = 0, 0, 0
for i in range(100):
    c, w, v = genere_instance()
    sol = prog_dyn(c, w, v)
    gp += glouton_poids(c, w, v)/sol
    gv += glouton_valeur(c, w, v)/sol
    gr += glouton_ratio(c, w, v)/sol
print(f"Glouton poids : {gp/100}")
print(f"Glouton valeur : {gv/100}")
print(f"Glouton ratio : {gr/100}")
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mZeroDivisionError[0m                         Traceback (most recent call last)
Cell [0;32mIn[19], line 5[0m
[1;32m      3[0m c, w, v [38;5;241m=[39m genere_instance()
[1;32m      4[0m sol [38;5;241m=[39m prog_dyn(c, w, v)
[0;32m----> 5[0m gp [38;5;241m+[39m[38;5;241m=[39m [43mglouton_poids[49m[43m([49m[43mc[49m[43m,[49m[43m [49m[43mw[49m[43m,[49m[43m [49m[43mv[49m[43m)[49m[38;5;241;43m/[39;49m[43msol[49m
[1;32m      6[0m gv [38;5;241m+[39m[38;5;241m=[39m glouton_valeur(c, w, v)[38;5;241m/[39msol
[1;32m      7[0m gr [38;5;241m+[39m[38;5;241m=[39m glouton_ratio(c, w, v)[38;5;241m/[39msol

[0;31mZeroDivisionError[0m: division by zero

