Traceback (most recent call last):
  File "/home/aquathi/.local/share/pipx/venvs/jupyter-book/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/aquathi/.local/share/pipx/venvs/jupyter-book/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aquathi/.local/share/pipx/venvs/jupyter-book/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/aquathi/.local/share/pipx/venvs/jupyter-book/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/aquathi/.local/share/pipx/venvs/jupyter-book/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/aquathi/.local/share/pipx/venvs/jupyter-book/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
classes, centres = k_moyennes(4)
for i in range(len(centres)):
    print("Centre", i, ":", inverse_standardisation(centres[i]))
    for j in classes[i]:
        print(" ", noms[j])
    print()

plot_precision(5)
------------------

----- stdout -----
Centre 0 : [4334.5, 545.0, 452.0, 195.0, 115.0, 1242.5, 327.0, 4.3, 17.0]
  ['carrera gt', 'porsche']
  ['f40', 'ferrari']

Centre 1 : [1178.75, 76.25, 388.5, 169.5, 149.5, 1045.75, 165.25, 14.25, 4.975]
  ['panda', 'fiat']
  ['208', 'peugeot']
  ['c3', 'citroÃ«n']
  ['clio 4', 'renault']

Centre 2 : [1682.25, 118.25, 413.75, 177.5, 147.75, 1259.25, 200.5, 9.05, 6.625]
  ['tt', 'audi']
  ['mÃ©gane 1', 'renault']
  ['2008', 'peugeot']
  ['captur', 'renault']

Centre 3 : [1563.6666666666667, 99.0, 442.0, 179.66666666666666, 172.33333333333334, 1658.3333333333333, 171.66666666666666, 13.666666666666668, 8.033333333333333]
  ['berlingo', 'citroÃ«n']
  ['espace', 'renault']
  ['scÃ©nic', 'renault']
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[28], line 8[0m
[1;32m      5[0m         [38;5;28mprint[39m([38;5;124m"[39m[38;5;124m [39m[38;5;124m"[39m, noms[j])
[1;32m      6[0m     [38;5;28mprint[39m()
[0;32m----> 8[0m [43mplot_precision[49m([38;5;241m5[39m)

[0;31mNameError[0m: name 'plot_precision' is not defined

