Traceback (most recent call last):
  File "/home/aquathi/.local/share/pipx/venvs/jupyter-book/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/aquathi/.local/share/pipx/venvs/jupyter-book/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aquathi/.local/share/pipx/venvs/jupyter-book/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/aquathi/.local/share/pipx/venvs/jupyter-book/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/aquathi/.local/share/pipx/venvs/jupyter-book/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/aquathi/.local/share/pipx/venvs/jupyter-book/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
longestIncreasingPath(m1)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[24], line 1[0m
[0;32m----> 1[0m [43mlongestIncreasingPath[49m[43m([49m[43mm1[49m[43m)[49m

Cell [0;32mIn[23], line 45[0m, in [0;36mlongestIncreasingPath[0;34m(mat)[0m
[1;32m     44[0m [38;5;28;01mdef[39;00m [38;5;21mlongestIncreasingPath[39m(mat):
[0;32m---> 45[0m     d [38;5;241m=[39m [[[38;5;241m0[39m][38;5;241m*[39m[38;5;28mlen[39m(matrix[[38;5;241m0[39m]) [38;5;28;01mfor[39;00m _ [38;5;129;01min[39;00m [38;5;28mrange[39m([38;5;28mlen[39m([43mmatrix[49m))]
[1;32m     46[0m     max_coords[38;5;241m=[39m([38;5;241m0[39m,[38;5;241m0[39m)
[1;32m     47[0m     maxi [38;5;241m=[39m [38;5;241m0[39m

[0;31mNameError[0m: name 'matrix' is not defined

